### ISSUE TITLE
Suave 2.6.0 support

### ISSUE THREAD

**Issue by lydell** [Zaid-Ajaj/Suave.SerilogExtensions#1]
Hi! Thanks for the great package!

Would it be possible to update to Suave 2.6.0?

**Comment by Zaid-Ajaj** [comment]
Hi @lydell, the library works with `Suave >= 2.5.0` so `Suave 2.6.0` should be compatible. Is this not the case and it doesn't work with Suave 2.6.0?

**Comment by lydell** [comment]
I got this error at runtime when trying to update to Suave 2.6.0:

```
Could not load file or assembly 'Suave, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
```

The error went away when commenting out Suave.SerilogExtensions.

I also noticed the release notes for 0.4.0 says “Update Suave dependency to 2.5.0” so I thought it was a thing to update this library with support for newer Suave versions.

In the end, I had to update to Suave 2.6.0 because of another dependency. To get unblocked, I temporarily copied this library into my code. It worked _almost_ out of the box. `context.userState` is apparently a `Dictionary` instead of a `Map` now, so I had to change those to get it compiling.

Hope this helps!

**Comment by Zaid-Ajaj** [comment]
I see, then it makes sense why it doesn't compile for Suave 2.6.0 since the types have changed. I will look into releasing a new version soon when time permits. Glad to hear you have a workaround for now 😄

**Comment by swuecho** [comment]
with Suave 2.5.6, similar exception.

` System.IO.FileLoadException: Could not load file or assembly 'Suave, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
`

**Comment by TheAngryByrd** [comment]
+1

**Comment by AlexeyRaga** [comment]
I am having the same issue:

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Suave, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Suave, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null'
```

@Zaid-Ajaj  any suggestions / workaround?

**Comment by Zaid-Ajaj** [comment]
Sorry @AlexeyRaga totally forgot about this issue 😓 thanks for the ping! A workaround for now is to downgrade to Suave v2.5 until I fix this (today or the next couple of days)

**Comment by Zaid-Ajaj** [comment]
Published Suave.SerilogExtensions v0.6.0 with updated latest dependencies 🚀
